### ISSUE TITLE
Should probably deal more gracefully with campfire throttling

### ISSUE THREAD

**Issue by deorth** [mmichie/luckystrike#12]
It appears that the campfire api has a throttle.

Not entirely sure the best way to handle this, but I'm concerned that requests are getting dropped :

``` python
2014-06-25 14:00:25-0700 [HttpStreamProtocol (TLSMemoryBIOProtocol),client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/luckystrike/httpstream.py", line 100, in lineReceived
            self.factory.consumer.messageReceived(message)
          File "/usr/lib/python2.7/site-packages/luckystrike/stream.py", line 29, in messageReceived
            d.callback(message)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 382, in callback
            self._startRunCallbacks(result)
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 490, in _startRunCallbacks
            self._runCallbacks()
        --- <exception caught here> ---
          File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 577, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
          File "/usr/lib/python2.7/site-packages/luckystrike/route.py", line 31, in route_incoming_message
            user = config.campfire.user(message['user_id'])['user']
          File "/usr/lib/python2.7/site-packages/pinder/campfire.py", line 64, in user
            return self._connector.get("users/%s" % user_id)
          File "/usr/lib/python2.7/site-packages/pinder/connector.py", line 27, in get
            return self._request('GET', path, data, headers, parse_body=parse_body)
          File "/usr/lib/python2.7/site-packages/pinder/connector.py", line 83, in _request
            self.response.status, str(e), body))
        exceptions.Exception: Something did not work fine: HTTP 503 - No JSON object could be decoded - You have exceeded 500 web requests in a 10-second period. Please wait 10 seconds before retrying.
```

**Comment by mmichie** [comment]
Closing as project is archived.

**Comment by mmichie** [comment]
Closed without fixing, project archived.
